Repository 1ronPark/Front-end, pull requests merged in 2025-07, with the labels that each got.

#7 feat:css구현 & tailwind v4 설치
  package.json
  src/App.css
  src/assets/fonts/NotoSansKR-Thin.woff2
  src/index.css
  vite.config.ts
  yarn.lock
Labels: ✨ Feat

#9 Design: top navbar UI 기본 기능 구현
  package.json
  src/App.tsx
  src/assets/ic_loginbutton.svg
  src/assets/ic_myprofile.svg
  src/assets/ic_search.svg
  src/assets/logo_lightup.svg
  src/components/common/.gitkeep
  src/components/common/mainNavbar/MainNavbar.tsx
  src/components/common/mainNavbar/SearchInput.tsx
  src/components/layout/.gitkeep
  src/components/layout/Layout.tsx
  src/pages/LightTalk.tsx
  src/pages/Members.tsx
  src/pages/MyProfile.tsx
  src/pages/Projects.tsx
  yarn.lock
Labels: 🎨 Design

#13 Design: Filter UI 디자인 완성
  package.json
  src/assets/icons/checkicon.svg
  src/assets/icons/ic_arrow_right.svg
  src/assets/icons/ic_check.svg
  src/assets/icons/ic_check_blue.svg
  src/assets/icons/ic_keyboard_arrow_down.svg
  src/assets/icons/ic_keyboard_arrow_up.svg
  src/assets/icons/ic_search.svg
  src/assets/searchicon.svg
  src/components/common/filter/FilterBar.tsx
  src/components/common/filter/dropdowns/ArrayBox.tsx
  src/components/common/filter/dropdowns/LocationBox.tsx
  src/components/common/filter/dropdowns/MbtiBox.tsx
  src/components/common/filter/dropdowns/SearchLocation.tsx
  src/data/locationData.ts
  src/pages/Members.tsx
  src/pages/Projects.tsx
  yarn.lock
Labels: 🎨 Design

#21 Design: Footbar UI 디자인 및 최신 상태 반영 완료
  src/App.css
  src/assets/fonts/PretendardVariable.woff2
  src/components/common/footbar/Footbar.tsx
  src/components/layout/Layout.tsx
Labels: 🎨 Design

#24 Design: 마이페이지 사이드바 ui 구현 및 파일구조 확립
  src/assets/icons/mypage/ic_code.svg
  src/assets/icons/mypage/ic_id_card.svg
  src/assets/icons/mypage/ic_person.svg
  src/components/mypage/MyInfo.tsx
  src/components/mypage/MyProfileEdit.tsx
  src/components/mypage/MyProjects.tsx
  src/components/mypage/MypageSidebar.tsx
  src/pages/MyProfile.tsx
Labels: 🎨 Design

#27 Design: 팀원 찾아보기 탭 공통 컴포넌트 구현하기
  mockData/dummyMemberInfo.tsx
  package.json
  src/App.tsx
  src/assets/icons/ic_avatar.svg
  src/assets/icons/ic_memberlocation.svg
  src/components/common/memberpage/MemberCard.tsx
  src/components/common/memberpage/MemberList.tsx
  src/components/layout/Layout.tsx
  src/pages/Members.tsx
  src/pages/member/MemberProfile.tsx
  src/pages/member/Members.tsx
  yarn.lock
Labels: 🎨 Design

#33 Design: 로그인 & 회원가입 페이지 디자인
  src/App.tsx
  src/assets/icons/ic_close.svg
  src/components/auth/AuthHeader.tsx
  src/pages/Auth/LoginForm.tsx
  src/pages/Auth/LoginPassword.tsx
  src/pages/Auth/PasswordReset.tsx
  src/pages/Auth/SignupForm.tsx
  src/pages/Auth/SignupPassword.tsx
Labels: 🎨 Design

#34 Design: 마이페이지 - 회원정보 UI & 필요한 모달 UI
  src/assets/icons/mypage/ic_camera.svg
  src/components/mypage/edit/Portfolio.tsx
  src/components/mypage/modal/AddPhotoModal.tsx
  src/components/mypage/modal/MyInfoEditModal.tsx
  src/components/mypage/modal/PortfolioModal.tsx
  src/components/mypage/myInfo/MyInfo.tsx
Labels: 🎨 Design

#43 Fix: 회원정보 레이아웃 수정 & 사이드바 액션 추가 && 마이페이지 메인네브바에서 연결
  src/App.tsx
  src/components/common/mainNavbar/MainNavbar.tsx
  src/components/common/sideNavbar/BasePanel.tsx
  src/components/common/sideNavbar/SideNavbar.tsx
  src/components/common/sideNavbar/favorite/FavoritePanel.tsx
  src/components/common/sideNavbar/notification/NotificationPanel.tsx
  src/components/layout/Layout.tsx
  src/components/mypage/MyPageInfo.tsx
  src/components/mypage/modal/MyInfoEditModal.tsx
  src/pages/MyProfile.tsx
Labels: 🐞 Fix, 🎨 Design

#50 Design: Mypage - 프로젝트 탭 UI 완성
  mockData/dummyProjectCard.tsx
  src/assets/icons/mypage/ic_group_search.svg
  src/assets/icons/mypage/ic_hail.svg
  src/assets/icons/mypage/ic_project_addsvg.svg
  src/assets/icons/mypage/project_empty.png
  src/assets/icons/mypage/project_sample_logo.png
  src/components/common/filter/ProjectFilterBar.tsx
  src/components/mypage/MyProfileEdit.tsx
  src/components/mypage/MyProjects.tsx
  src/components/mypage/MypageSidebar.tsx
  src/components/mypage/edit/Reception.tsx
  src/components/mypage/project/MyProjectEmpty.tsx
  src/components/mypage/project/MyProjectList.tsx
  src/components/mypage/project/MyprojectCard.tsx
  src/pages/MyProfile.tsx
  src/types/MyProjectCard.ts
Labels: 🎨 Design

#54 Update PR templates
  .github/ISSUE_TEMPLATE/custom-pr-template.md
  .github/ISSUE_TEMPLATE/custom.md
Labels: 📃 Docs

#56 Fix: 팀원 찾아보기 페이지 수정 사항 반영
  mockData/dummyMemberInfo.tsx
  package.json
  public/dev_portfolio.pdf
  src/assets/icons/ic_github.svg
  src/assets/icons/ic_issupported.svg
  src/assets/icons/ic_member_email.svg
  src/assets/icons/ic_member_location.svg
  src/assets/icons/ic_member_part.svg
  src/assets/icons/ic_member_univ.svg
  src/assets/icons/ic_profile.svg
  src/assets/icons/ic_send.svg
  src/components/common/mainNavbar/MainNavbar.tsx
  src/components/common/memberpage/MemberAwards.tsx
  src/components/common/memberpage/MemberCard.tsx
  src/components/common/memberpage/MemberList.tsx
  src/components/common/memberpage/MemberPortfolio.tsx
  src/components/common/memberpage/MemberProfileCard.tsx
  src/components/common/memberpage/MemberStrengths.tsx
  src/components/common/modals/SupportAlert.tsx
  src/components/layout/Layout.tsx
  src/pages/member/MemberDetail.tsx
  src/types/MyInfoProps.ts
  yarn.lock
Labels: ✨ Feat, 🎨 Design

#61 Feat: api 호출 컴포넌트 생성
  src/utils/.gitkeep
  src/utils/checkAuth.ts
  src/utils/fetchRequest.ts
  src/utils/serverCall.ts
Labels: 📬 API, ✨ Feat

#64 Design: 프로젝트, 팀원 알아보기 공통 모달 제작
  src/assets/icons/ic_sendresume.svg
  src/components/common/memberpage/MemberProfileCard.tsx
  src/components/common/modals/ActionStatusModal.tsx
  src/components/common/modals/AlertModal.tsx
  src/components/common/modals/SupportAlert.tsx
  src/components/layout/Layout.tsx
Labels: ✨ Feat, 🎨 Design
