Repository 1ronPark/Front-end, pull requests merged in 2025-08, with the labels that each got.

#74 Chore: 초기화 로직 구현 x
  src/hooks/apiHooks.ts
  src/hooks/fetchRequest.ts
  src/hooks/useJoin.ts
  src/hooks/useUser.ts
  src/pages/Auth/PasswordReset.tsx
  src/store/useAuthStore.ts
Labels: ✨ Feat

#83 Feat: 팀원 탐색 기능 구현
  src/components/common/memberpage/MemberCard.tsx
  src/components/common/memberpage/MemberPortfolio.tsx
  src/components/common/memberpage/MemberProfileCard.tsx
  src/components/layout/Layout.tsx
  src/hooks/useMember.ts
  src/pages/member/MemberDetail.tsx
  src/pages/member/Members.tsx
  src/types/MemberProps.ts
  yarn.lock
Labels: ✨ Feat, 🎨 Design

#86 Chore: sync develop with main
  .gitignore
  mockData/dummyMemberInfo.tsx
  src/components/common/cards/historys/History.tsx
  src/components/common/memberpage/MemberCard.tsx
  src/hooks/useMember.ts
  src/types/MyInfoProps.ts
Labels: 🔧 Chore

#85 Refator: 비밀번호변경 부분에서 기존 비번 확인하는 api 연결 완료
  src/components/mypage/passwordChange/PasswordChangeForm.tsx
  src/hooks/usePasswordCheck.ts
Labels: 🔨 Refactor

#88 Refactor: 사이드바 수정 & 마이페이지 컨텐츠 가운데 정렬
  src/assets/sideNavbar/history.svg
  src/components/common/sideNavbar/SideNavbar.tsx
  src/components/common/sideNavbar/favorite/FavoriteItem.tsx
  src/components/common/sideNavbar/favorite/FavoriteList.tsx
  src/components/common/sideNavbar/notification/NoticeItem.tsx
  src/components/common/sideNavbar/recent/NoRecentList.tsx
  src/components/common/sideNavbar/recent/RecentList.tsx
  src/components/mypage/MyPageInfo.tsx
  src/components/mypage/MyProfileEdit.tsx
  src/components/mypage/MyProjects.tsx
Labels: 🔨 Refactor

#94 Deisgn: 공통 툴팁 제작
  package.json
  src/components/common/memberpage/MemberProfileCard.tsx
  src/components/common/projectsdetail/ProjectInfoCard.tsx
  src/components/common/tooltips/ToolTip.tsx
  src/pages/member/MemberDetail.tsx
  yarn.lock
Labels: ✨ Feat, 🎨 Design

#104 feat: 소셜로그인 구현 완료
  package.json
  src/hooks/useLogin.ts
  src/pages/Auth/LoginPassword.tsx
  src/pages/Auth/SocialCallback.tsx
Labels: ✨ Feat

#108 Fix: typescript mismatch
  index.html
  mockData/dummyLightTalkCard.tsx
  mockData/dummyLightTalkComment.tsx
  src/assets/icons/ic_issupported.svg
  src/assets/icons/ic_life.svg
  src/assets/icons/ic_profile.svg
  src/assets/icons/ic_sendresume.svg
  src/components/common/buttons/LikeButton.tsx
  src/components/common/projects/ProjectCard.tsx
  src/components/common/projects/ProjectList.tsx
  src/components/common/projectsdetail/ProjectInfoCard.tsx
  src/components/mypage/MyPageInfo.tsx
  src/components/mypage/edit/Header.tsx
  src/components/mypage/edit/ModifyingMenu.tsx
  src/components/mypage/edit/Portfolio.tsx
  src/components/mypage/modal/UnivVerifyModal.tsx
  src/components/mypage/passwordChange/PasswordChangeForm.tsx
  src/hooks/fetchRequest.ts
  src/hooks/useChangePassword.ts
  src/hooks/useJoin.ts
  src/hooks/useLogin.ts
  src/hooks/useMakeItem.ts
  src/hooks/useMyProjects.ts
  src/hooks/usePositions.ts
  src/hooks/useProfile.ts
  src/hooks/useProject.ts
  src/hooks/useRegion.ts
  src/hooks/useUser.ts
  src/lib/axios.ts
  src/pages/Auth/LoginForm.tsx
  src/pages/Auth/SignupPassword.tsx
  src/pages/LightTalk.tsx
  src/pages/lightTalk/CommentItem.tsx
  src/pages/lightTalk/TalkBox.tsx
  src/pages/lightTalk/TalkCardDetail.tsx
  src/pages/lightTalk/TalkList.tsx
  src/pages/project/ProjectDetails.tsx
  src/types/LightTalkProps.ts
  src/types/MyInfoProps.ts
  src/types/ProjectCardWithUser.ts
  vercel.json
  vite.config.ts
Labels: 🌏 Deploy

#122 Feat: 팀원 API 연결
  src/components/common/filter/MemberFilterBar.tsx
  src/components/common/memberpage/MemberAwards.tsx
  src/components/common/memberpage/MemberCard.tsx
  src/components/common/memberpage/MemberList.tsx
  src/components/common/memberpage/MemberPortfolio.tsx
  src/components/common/memberpage/MemberProfileCard.tsx
  src/components/common/memberpage/MemberStrengths.tsx
  src/components/common/modals/SearchModal.tsx
  src/hooks/useDebounce.ts
  src/hooks/useMember.ts
  src/pages/member/MemberDetail.tsx
  src/pages/member/Members.tsx
  src/types/MemberProps.ts
  src/types/MyInfoProps.ts
  src/utils/buildMemberParams.ts
  src/utils/formatRegions.ts
Labels: 📬 API, ✨ Feat

#139 Fix: 마이페이지에서 프로필이미지 변경 & 선호지역등록 에러난 부분 수정완료
  src/components/mypage/MyPageInfo.tsx
  src/hooks/useProfile.ts
  src/hooks/useRegion.ts
  src/pages/FormEdit.tsx
Labels: 🐞 Fix

#147 Feat: 프로젝트 지원 내 프로젝트 구분
  src/App.tsx
  src/components/common/buttons/Switch.tsx
  src/components/common/modals/ProjectDeleteModal.tsx
  src/components/common/modals/ProjectEditDeleteModal.tsx
  src/components/common/projectsdetail/ProjectInfoCard.tsx
  src/components/mypage/MyProjects.tsx
  src/components/mypage/RegisterProject.tsx
  src/components/mypage/project/MyProjectList.tsx
  src/components/mypage/project/MyprojectCard.tsx
  src/components/mypage/project/register/Detail.tsx
  src/components/mypage/project/register/Header.tsx
  src/components/mypage/project/register/ProjectMenu.tsx
  src/components/mypage/project/register/Recruit.tsx
  src/components/mypage/project/register/Save.tsx
  src/hooks/apiHooks.ts
  src/hooks/useDeleteProject.ts
  src/hooks/useGetProjectInfo.ts
  src/hooks/useMakeItem.ts
  src/hooks/useMyProjects.ts
  src/hooks/usePatchProject.ts
  src/pages/MyProfile.tsx
  src/store/editProjectStore.ts
  src/store/registerProjectStore.ts
  src/types/ProjectDetailProps.ts
Labels: ✨ Feat, 🔨 Refactor

#150 Feat: 프로젝트 카드 개선 (소개글·학교명 표시 + 댓글 등록 실시간 반영)
  src/components/common/comment/CommentSection.tsx
  src/components/common/filter/ProjectFilterBar.tsx
  src/components/common/projects/ProjectCard.tsx
  src/components/common/projects/ProjectList.tsx
  src/components/common/projectsdetail/ProjectInfoCard.tsx
  src/components/common/projectsdetail/RecruitPart.tsx
  src/components/mypage/MyProjects.tsx
  src/components/mypage/project/MyprojectCard.tsx
  src/components/mypage/project/register/Save.tsx
  src/hooks/useMyProjects.ts
  src/hooks/useProject.ts
  src/hooks/useProjectComment.ts
  src/hooks/useProjectQueries.ts
  src/pages/project/ProjectDetails.tsx
  src/pages/project/Projects.tsx
  src/types/ProjectDetailContext.tsx
  src/types/ProjectProps.ts
  src/utils/categoryMap.tsx
Labels: ✨ Feat

#167 Docs: Update README.md
  README.md
Labels: 📃 Docs
